### ISSUE TITLE
Отскрэйпить несколько магазинов 

### ISSUE THREAD

**Issue by BabenkoY** [openworld-community/Peredelano-Prices#1]
Todo: Отскрэйпить несколько магазинов на примере доставки "Глобал" (Черногория)
Скрэйпить необходимо все продукты, которые есть на сайте магазина или доставки для сравнения между собой.
![Снимок экрана 2023-06-22 в 22 53 31](https://github.com/openworld-community/Peredelano-Prices/assets/136717943/65b551ec-24ec-427b-9d9d-9874e9bb1caf)

**Comment by aurum447** [comment]
Glovo
